### ISSUE TITLE
broken deployment - dependencies removed from epel package repo

### ISSUE THREAD

**Issue by adampalm** [aws-samples/aws-gateway-load-balancer-suricata-ids-ips-nsm#22]
the bundle 'libmaxminddb-devel' has been removed from the epel repo, used by ./amazon-linux-extras. This will need to be built from source.

**Comment by jespereneberg** [comment]
Fixed in #23

**Comment by adampalm** [comment]
reopening - this worked in testing but not on a fresh deployment. Suspect that it's related to the testing method ( fix already synthesized )
